markdown: kramdown
highlighter: rouge
permalink: '/:title/'
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-mentions
  # - jekyll-cache  <-- REMOVED jekyll-cache from the plugins list

# Removed the entire jekyll-cache configuration section:
# jekyll-cache:
#   enabled: true

include:
  - node_modules  # You probably need this for your Parcel/Webpack setup
title: Driftlight
author:
  name: Congyue Wang
  email: to.me@wcy.one
  url: 'https://gallery.wcy.one'
description: "A photo gallery"
repository: wzwtt/Gallery
github: 'https://github.com/wzwtt/Gallery'
feed:
  path: rss-feed.xml
sitemap:
  url: 'https://gallery.wcy.one' #this is redundant
jekyll-seo-tag:
  title: Driftlight
  description: Wandering through cities, pixels, and memories—chasing light with no map in hand.
  image: /assets/svg/favicon.svg
jekyll-mentions:
  base_url: 'https://x.com'
favicon: /assets/svg/favicon.svg

# Removed caching and cache_dir. Jekyll 4+ handles this automatically.
# caching: true
# cache_dir: _cache

#google_analytics: 
header:
  title: Driftlight
  tagline: Wandering through cities, pixels, and memories—chasing light with no map in hand.
  image: /assets/svg/favicon.svg